resources:
  - name: repo
    type: git
    icon: github
    source:
      uri: https://github.com/mattcl/aoc2022.git

jobs:
  - name: test-and-bench
    public: true
    build_log_retention:
      builds: 50
    plan:
      - get: repo
        trigger: true
      - task: test-and-bench
        file: repo/ci/tasks/test-and-bench.yaml
